export type ProgramTrack = {
  id: string;
  title: string;
  shortTitle: string;
  detail: string;
  badge: string;
  format: string;
  image: string;
  imageAlt: string;
  focus: string;
  support: string;
  eyebrow: string;
  headline: string;
  description: string;
  outcomes: string[];
  bestFor: string;
};

export const programTracks: ProgramTrack[] = [
  {
    id: "programa-por-niveles",
    title: "Programa de inglés por niveles",
    shortTitle: "Ruta completa",
    detail: "Una ruta de cuatro niveles, cada uno estructurado en 14 módulos, que integra conversación, comprensión auditiva, lectura y escritura.",
    badge: "4 niveles",
    format: "Online",
    image: "/images/program-academic-career-portrait.webp",
    imageAlt: "Estudiante participando en un programa de inglés online por niveles",
    focus: "14 módulos",
    support: "Evaluación continua",
    eyebrow: "Avance progresivo",
    headline: "Construya una base sólida y avance hacia conversaciones cada vez más naturales.",
    description:
      "El programa completo se proyecta a dos años. Durante los primeros tres meses, la ruta apunta a construir una base aproximada de 300 a 500 palabras para comenzar conversaciones reales; el resultado depende de la asistencia y la práctica de cada estudiante.",
    outcomes: ["Vocabulario funcional", "Las cuatro habilidades", "Conversación guiada", "Certificado de finalización"],
    bestFor: "Personas principiantes o de nivel intermedio que desean una ruta completa, ordenada y de largo plazo.",
  },
  {
    id: "clases-individuales",
    title: "Clases privadas de inglés",
    shortTitle: "Atención 1 a 1",
    detail: "Sesiones privadas adaptadas a su nivel, ritmo, objetivos y necesidades de comunicación.",
    badge: "Uno a uno",
    format: "Online",
    image: "/images/program-live-speaking-portrait.webp",
    imageAlt: "Estudiante practicando inglés en una clase individual online",
    focus: "Plan personal",
    support: "Corrección directa",
    eyebrow: "Atención personalizada",
    headline: "Trabaje exactamente lo que necesita, con seguimiento cercano de Alberto.",
    description:
      "Cada clase se adapta a su nivel y a la forma en que utilizará el idioma. Puede enfocarse en conversación, gramática aplicada, pronunciación, comprensión, escritura o una combinación de estas áreas.",
    outcomes: ["Más seguridad al hablar", "Corrección personalizada", "Ritmo flexible", "Objetivos concretos"],
    bestFor: "Profesionales, universitarios y adultos que valoran la atención individual y un plan ajustado a su realidad.",
  },
  {
    id: "clases-grupales",
    title: "Clases grupales de inglés",
    shortTitle: "Aprendizaje en grupo",
    detail: "Práctica estructurada con estudiantes de nivel similar, dos veces por semana.",
    badge: "Grupos por nivel",
    format: "2 días por semana",
    image: "/images/online-english-session.webp",
    imageAlt: "Grupo de estudiantes en una clase de inglés online",
    focus: "Interacción real",
    support: "2 horas por clase",
    eyebrow: "Aprenda acompañado",
    headline: "Practique, escuche y gane soltura en un grupo alineado con su nivel.",
    description:
      "Las clases grupales combinan explicación, conversación, lectura, ejercicios y práctica. Los grupos se organizan por nivel para que cada estudiante pueda participar y avanzar con una base adecuada.",
    outcomes: ["Práctica conversacional", "Trabajo colaborativo", "Rutina constante", "Progreso por nivel"],
    bestFor: "Estudiantes que desean una estructura fija, interacción con otros participantes y una inversión mensual accesible.",
  },
  {
    id: "tutorias-personalizadas",
    title: "Tutorías personalizadas",
    shortTitle: "Apoyo puntual",
    detail: "Sesiones para resolver una necesidad específica por día, por semana o según el objetivo.",
    badge: "Enfoque específico",
    format: "Flexible",
    image: "/images/program-writing-track-portrait.webp",
    imageAlt: "Estudiante recibiendo una tutoría personalizada de inglés online",
    focus: "Dudas concretas",
    support: "Práctica dirigida",
    eyebrow: "Resuelva lo que le frena",
    headline: "Obtenga apoyo preciso sin inscribirse en un programa completo.",
    description:
      "Las tutorías están pensadas para estudiantes que necesitan reforzar un tema, preparar una asignación, mejorar un texto, practicar una presentación o aclarar una dificultad puntual.",
    outcomes: ["Explicación clara", "Práctica focalizada", "Apoyo académico", "Sesiones flexibles"],
    bestFor: "Estudiantes que ya tienen una meta o dificultad específica y necesitan orientación profesional para resolverla.",
  },
  {
    id: "coaching-especializado",
    title: "Coaching especializado",
    shortTitle: "Metas profesionales",
    detail: "Preparación enfocada para entrevistas, exámenes, negocios, viajes y pronunciación.",
    badge: "Objetivos reales",
    format: "Plan a medida",
    image: "/images/program-academic-career-portrait.webp",
    imageAlt: "Profesional preparándose para una entrevista en inglés",
    focus: "Entrevistas y exámenes",
    support: "Contexto y cultura",
    eyebrow: "Prepárese con intención",
    headline: "Llegue a ese momento importante con lenguaje, práctica y criterio.",
    description:
      "El coaching parte de una situación concreta: una entrevista laboral, un examen, una conversación de negocios, un viaje o una dificultad de pronunciación. Cada sesión trabaja el vocabulario y el contexto que realmente necesitará.",
    outcomes: ["Respuestas más claras", "Vocabulario relevante", "Práctica contextual", "Mayor preparación"],
    bestFor: "Personas con una fecha, oportunidad o reto específico que requiere preparación intensiva y relevante.",
  },
  {
    id: "espanol-para-extranjeros",
    title: "Español para extranjeros",
    shortTitle: "Spanish coaching",
    detail: "Clases prácticas de español para comunicarse con confianza en situaciones reales.",
    badge: "Español",
    format: "Online",
    image: "/images/spanish-for-foreigners-online.webp",
    imageAlt: "Estudiante extranjero aprendiendo español en una sesión online",
    focus: "Comunicación práctica",
    support: "Contexto cultural",
    eyebrow: "Spanish for real life",
    headline: "Aprenda español para comunicarse con claridad en situaciones reales.",
    description:
      "Alberto Academy también ofrece enseñanza de español para personas de habla inglesa. El plan se adapta a viajes, trabajo, vida cotidiana, estudios o integración cultural.",
    outcomes: ["Conversación práctica", "Pronunciación guiada", "Vocabulario cotidiano", "Comprensión cultural"],
    bestFor: "Extranjeros de habla inglesa que desean aprender español con una guía clara, progresiva y personalizada.",
  },
];

export const programTracksEn: ProgramTrack[] = [
  {
    id: "programa-por-niveles",
    title: "Spanish program by level",
    shortTitle: "Complete pathway",
    detail: "A four-level pathway that develops speaking, listening, reading, and writing in a clear sequence.",
    badge: "4 levels",
    format: "Online",
    image: "/images/program-academic-career-portrait.webp",
    imageAlt: "Student progressing through an online Spanish program",
    focus: "14 modules",
    support: "Ongoing assessment",
    eyebrow: "Progressive learning",
    headline: "Build a strong foundation, then move toward natural Spanish conversations.",
    description: "The full program is designed as a two-year pathway. In the first three months, the goal is to build a practical base of roughly 300 to 500 words so you can begin forming real conversations. Results depend on attendance and practice.",
    outcomes: ["Practical vocabulary", "Four language skills", "Guided conversation", "Completion certificate"],
    bestFor: "Beginners and intermediate learners who want a complete, organized, long-term Spanish pathway.",
  },
  {
    id: "clases-individuales",
    title: "Private Spanish lessons",
    shortTitle: "One-to-one attention",
    detail: "Personalized sessions built around your level, pace, goals, and real communication needs.",
    badge: "One to one",
    format: "Online",
    image: "/images/program-live-speaking-portrait.webp",
    imageAlt: "Student practicing Spanish in a private online lesson",
    focus: "Personal plan",
    support: "Direct feedback",
    eyebrow: "Personalized attention",
    headline: "Work on the Spanish you actually need, with Alberto guiding every step.",
    description: "Your lessons adapt to how you plan to use Spanish. Sessions can combine conversation, practical grammar, pronunciation, listening, writing, and vocabulary for travel, work, relocation, or daily life.",
    outcomes: ["More confidence speaking", "Personal feedback", "Flexible pace", "Clear goals"],
    bestFor: "Adults, professionals, travelers, and newcomers who value personal attention and a plan shaped around real life.",
  },
  {
    id: "clases-grupales",
    title: "Group Spanish lessons",
    shortTitle: "Learn together",
    detail: "Structured practice with learners at a similar level, meeting twice each week.",
    badge: "Level-based groups",
    format: "2 days per week",
    image: "/images/online-english-session.webp",
    imageAlt: "Students practicing Spanish together in an online class",
    focus: "Real interaction",
    support: "2-hour lessons",
    eyebrow: "Practice with others",
    headline: "Listen, respond, and become more comfortable using Spanish with a group.",
    description: "Group lessons combine explanation, conversation, reading, exercises, and guided practice. Students are organized by level so everyone has a useful place in the conversation.",
    outcomes: ["Conversation practice", "Collaborative learning", "Consistent routine", "Level-based progress"],
    bestFor: "Learners who want a fixed schedule, interaction with others, and a more accessible monthly investment.",
  },
  {
    id: "tutorias-personalizadas",
    title: "Personalized Spanish tutoring",
    shortTitle: "Focused support",
    detail: "Flexible sessions for one specific challenge, assignment, presentation, or communication goal.",
    badge: "Focused help",
    format: "Flexible",
    image: "/images/program-writing-track-portrait.webp",
    imageAlt: "Student receiving personalized online Spanish tutoring",
    focus: "Specific questions",
    support: "Guided practice",
    eyebrow: "Solve what is holding you back",
    headline: "Get precise support without committing to a complete program.",
    description: "Tutoring is designed for learners who need to clarify a topic, improve a text, prepare a presentation, or work through a specific difficulty in Spanish.",
    outcomes: ["Clear explanations", "Focused practice", "Academic support", "Flexible sessions"],
    bestFor: "Learners with one defined goal who need professional support to move forward.",
  },
  {
    id: "coaching-especializado",
    title: "Specialized Spanish coaching",
    shortTitle: "Real-world goals",
    detail: "Targeted preparation for travel, relocation, work conversations, interviews, and pronunciation.",
    badge: "Practical goals",
    format: "Custom plan",
    image: "/images/program-academic-career-portrait.webp",
    imageAlt: "Professional preparing to communicate in Spanish at work",
    focus: "Work and travel",
    support: "Language and culture",
    eyebrow: "Prepare with purpose",
    headline: "Walk into an important Spanish-speaking moment prepared to take part.",
    description: "Coaching begins with one real situation: an upcoming trip, relocation, work meeting, interview, or pronunciation challenge. Each session focuses on the language and cultural context you will actually use.",
    outcomes: ["Clearer responses", "Relevant vocabulary", "Contextual practice", "Stronger preparation"],
    bestFor: "People with a specific date, opportunity, or challenge that calls for focused preparation.",
  },
  {
    id: "espanol-para-extranjeros",
    title: "English instruction",
    shortTitle: "English coaching",
    detail: "Practical English instruction for learners who need the language for work, study, travel, or daily life.",
    badge: "English",
    format: "Online",
    image: "/images/spanish-for-foreigners-online.webp",
    imageAlt: "Student learning English in a personalized online session",
    focus: "Practical communication",
    support: "Personal guidance",
    eyebrow: "English when you need it",
    headline: "English instruction is also available for learners who need a clear, practical path.",
    description: "While this English-language experience focuses on Spanish, Alberto also teaches English through level-based programs, private lessons, group classes, tutoring, and specialized coaching.",
    outcomes: ["Practical speaking", "Guided pronunciation", "Useful vocabulary", "Structured progress"],
    bestFor: "Learners who need English for professional, academic, travel, or everyday communication goals.",
  },
];
