import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarCheck, CheckCircle2, HeartHandshake, Quote, ShieldCheck, Sparkles, Star } from "lucide-react";
import { CountUpStat } from "@/components/count-up-stat";
import { MotionArticle, MotionImagePanel, MotionReveal } from "@/components/motion-reveal";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { localePath, type Locale } from "@/lib/i18n";
import { getRequestLocale } from "@/lib/i18n-server";
import { createLocalizedMetadata } from "@/lib/metadata";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getRequestLocale();
  return createLocalizedMetadata({
    locale,
    path: "/testimonials",
    ...(locale === "en"
      ? { title: "Student Results | Alberto Academy", description: "See how Alberto's students build confidence, clearer communication, and practical language skills, then explore Spanish lessons designed for real life." }
      : { title: "Testimonios | Alberto Academy", description: "Conoce las experiencias reales de estudiantes que ganaron confianza, fluidez y claridad al aprender inglés con Alberto Academy." }),
  });
}

const pageCopy = {
  es: {
    stats: [{ value: "200+", label: "Estudiantes formados" }, { value: "4+", label: "Años enseñando" }, { value: "4", label: "Niveles de aprendizaje" }, { value: "3", label: "Modalidades flexibles" }],
    stories: [
      { name: "Alondra I. Marte Grant", role: "Estudiante de inglés", quote: "El profesor Alberto A. Sosa cambió por completo mi forma de ver el inglés. Ya no tengo miedo de hablar y me siento mucho más segura al expresarme. Estoy muy agradecida por todo lo que aprendí y por el apoyo que recibí.", result: "Confianza al hablar", track: "Experiencia real" },
      { name: "Bilkia R. Pen Valdez", role: "Estudiante de inglés", quote: "Antes me daba mucho miedo hablar inglés porque pensaba que cometería demasiados errores. Usar el idioma era mi mayor temor, pero gracias a mi profesor Alberto A. Sosa ahora puedo comunicarme con mucha más confianza y hablar de una manera más natural.", result: "Comunicación natural", track: "Experiencia real" },
      { name: "Alexa W. Perez Valdez", role: "Estudiante de inglés", quote: "Comencé a estudiar inglés con el profesor Alberto A. Sosa a los 12 años y me gradué a los 15. Al principio, el idioma me parecía muy difícil y me daba miedo hablar, pero gracias a su paciencia y dedicación ahora puedo hablar inglés con fluidez y sin miedo.", result: "Fluidez sin miedo", track: "Experiencia real" },
      { name: "Wineliqui Valdez Diaz", role: "Estudiante de inglés", quote: "Podía entender inglés, pero me daba miedo hablar porque sentía que mi vocabulario era limitado y temía cometer errores gramaticales. Gracias a la paciencia, dedicación y motivación de mi profesor, gané más confianza y ahora me siento más cómoda al expresarme en inglés.", result: "Seguridad al expresarse", track: "Experiencia real" },
      { name: "Eufemia Rodriguez Sosa", role: "Estudiante de inglés", quote: "Antes me daba miedo escribir en inglés porque temía cometer errores. Gracias a la dedicación, el cariño y la paciencia de mi profesor, gané más confianza y comencé a disfrutar el proceso de aprendizaje. Estoy verdaderamente agradecida por su forma de enseñar y motivarnos.", result: "Confianza al escribir", track: "Experiencia real" },
      { name: "Rosa L. Polanco", role: "Estudiante de inglés", quote: "No tenía miedo de usar palabras en inglés justo después de aprenderlas, pero tenía dificultades por mi vocabulario limitado y para comprender ciertos temas. La orientación, el compromiso y el método de enseñanza de mi profesor me ayudaron a ampliar mi vocabulario y fortalecer mi comprensión.", result: "Vocabulario más amplio", track: "Experiencia real" },
      { name: "Rosa Maria Teresa", role: "Estudiante de inglés", quote: "Siempre disfruté hablar inglés, pero muchas veces me costaba encontrar las palabras correctas y comprender por completo las conversaciones. Este curso me ayudó a desarrollar un vocabulario más amplio y a comunicarme con mayor claridad. Agradezco la orientación, creatividad y compromiso de mi profesor para hacer que cada lección fuera útil y práctica.", result: "Claridad y comprensión", track: "Experiencia real" },
    ],
    outcomes: ["Pronunciación y estructura más claras", "Más confianza para hablar en situaciones reales", "Mejor escritura para estudiar y trabajar", "Práctica personalizada entre clases"],
    heroKicker: "Resultados de estudiantes", heroTitle: "Progreso real de estudiantes que querían usar el inglés con seguridad.", heroBody: "Estas experiencias muestran el tipo de progreso que impulsa Alberto Academy: hablar con mayor claridad, escribir mejor y comunicarse con confianza cuando el inglés importa.", heroPrimary: "Agendar conversación inicial", heroSecondary: "Leer testimonios", heroAlt: "Tres estudiantes adultos de inglés celebrando su graduación",
    featuredKicker: "Historia destacada", featuredTitle: "Una confianza que se nota fuera de clase.", featuredBody: "Los mejores resultados no son solo calificaciones o certificados. Se sienten cuando un estudiante habla con menos dudas, escribe con mayor control y usa el inglés en situaciones reales.", featuredImageAlt: "Estudiante de inglés después de ganar mayor confianza", stars: "Testimonio de cinco estrellas",
    gridKicker: "Más historias reales", gridTitle: "Metas diferentes. Un método práctico y cercano.", outcomeKicker: "Lo que mejora", outcomeTitle: "Un progreso que se nota semana tras semana.", outcomeBody: "Cada clase se conecta con un resultado práctico para que los estudiantes sepan qué están mejorando y cómo continuar practicando.",
    finalKicker: "Tu turno", finalTitle: "Empieza con una conversación inicial y descubre tu próximo paso.", finalBody: "Alberto revisará tu nivel, tus metas y tu disponibilidad para recomendarte la mejor ruta de inglés.", finalItems: ["Orientación de nivel", "Ruta personalizada", "Retroalimentación enfocada"], finalNote: "La conversación inicial permite identificar lo que ya dominas, lo que necesitas reforzar y el programa que mejor se adapta a tus metas.", finalPrimary: "Agendar conversación inicial", finalSecondary: "Explorar programas",
  },
  en: {
    stats: [{ value: "400+", label: "Students taught" }, { value: "4+", label: "Years teaching" }, { value: "4", label: "Learning levels" }, { value: "3", label: "Flexible formats" }],
    stories: [
      { name: "Alondra I. Marte Grant", role: "English student", quote: "Teacher Alberto A. Sosa completely changed the way I see English. I’m no longer afraid to speak, and I feel much more confident expressing myself. I’m really grateful for everything I learned and the support I received.", result: "Speaking confidence", track: "Real student experience" },
      { name: "Bilkia R. Pen Valdez", role: "English student", quote: "I used to be very afraid of speaking English because I thought I would make too many mistakes. My biggest fear was to use the language, but thanks to my teacher Alberto A. Sosa I can now communicate with much more confidence and speak more naturally.", result: "Natural communication", track: "Real student experience" },
      { name: "Alexa W. Perez Valdez", role: "English student", quote: "I started studying English with teacher Alberto A. Sosa at the age of 12 and graduated at 15. At first, the language seemed very difficult and I was afraid to speak, but thanks to his patience and dedication, now I can speak English fluently and fearlessly.", result: "Fluent, fearless speaking", track: "Real student experience" },
      { name: "Wineliqui Valdez Diaz", role: "English student", quote: "I could understand English, but I was afraid to speak because I felt my vocabulary was limited and I was scared of making grammar mistakes. Thanks to my teacher’s patience, dedication, and encouragement, I became more confident and comfortable expressing myself in English.", result: "Confident expression", track: "Real student experience" },
      { name: "Eufemia Rodriguez Sosa", role: "English student", quote: "I used to be afraid of writing in English because I was scared of making mistakes. Thanks to my teacher’s dedication, love, and patience, I gained more confidence and started enjoying the learning process. I am truly grateful for the way he teaches and encourages us.", result: "Writing confidence", track: "Real student experience" },
      { name: "Rosa L. Polanco", role: "English student", quote: "I wasn’t afraid to use English words right after learning them, but I struggled with a limited vocabulary and understanding certain topics. My teacher’s guidance, commitment, and effective teaching style helped me broaden my vocabulary and strengthen my comprehension.", result: "Stronger vocabulary", track: "Real student experience" },
      { name: "Rosa Maria Teresa", role: "English student", quote: "I always enjoyed speaking English, but I often struggled to find the right words and understand conversations completely. This course helped me develop a stronger vocabulary and communicate with greater clarity. I’m thankful for my teacher’s guidance, creativity, and commitment to making every lesson meaningful and practical.", result: "Clarity and comprehension", track: "Real student experience" },
    ],
    outcomes: ["Clearer pronunciation and sentence structure", "More confidence in meetings and interviews", "Better writing for school, work, and exams", "Personalized practice between live lessons"],
    heroKicker: "Student results", heroTitle: "A teaching method students can feel beyond class.", heroBody: "These real student stories show Alberto's communication-first approach in practice. The same structured, supportive method guides every Spanish lesson.", heroPrimary: "Book a Free Consultation", heroSecondary: "Read Stories", heroAlt: "Three happy adult language students celebrating their progress",
    featuredKicker: "Featured story", featuredTitle: "Confidence that follows you beyond the lesson.", featuredBody: "The strongest results appear when a student speaks with less hesitation, writes with more control, and uses the language in real situations.", featuredImageAlt: "Professional language student after building greater confidence", stars: "Five-star testimonial",
    gridKicker: "More student stories", gridTitle: "Different goals. One practical method.", outcomeKicker: "What improves", outcomeTitle: "Progress you can notice from week to week.", outcomeBody: "Every lesson connects to a practical result, so students know what is improving and what to practice next.",
    finalKicker: "Your turn", finalTitle: "Start with a free consultation and leave with a clear Spanish path.", finalBody: "Alberto will review your level, goals, and schedule, then recommend the learning format that fits your next step.", finalItems: ["Level guidance", "Personal roadmap", "Focused feedback"], finalNote: "The consultation identifies what you already know, what you need most, and which Spanish program fits your goals.", finalPrimary: "Book a Free Consultation", finalSecondary: "Explore Programs",
  },
};

export default async function TestimonialsPage() {
  const locale = await getRequestLocale();
  const c = pageCopy[locale];
  return <main className="min-h-screen bg-surface-cream text-brand-navy"><SiteHeader locale={locale} /><Hero locale={locale} c={c} /><StatsBand c={c} /><FeaturedStory c={c} /><StoryGrid c={c} /><OutcomeSection c={c} /><FinalCTA locale={locale} c={c} /><SiteFooter locale={locale} /></main>;
}

type Copy = (typeof pageCopy)[Locale];

function Hero({ locale, c }: { locale: Locale; c: Copy }) {
  return <section id="testimonials-hero" className="relative isolate overflow-hidden bg-brand-navy px-4 pb-20 pt-14 text-white sm:px-6 sm:pb-24 sm:pt-16 lg:px-8 lg:pb-32 lg:pt-20"><div className="orbital-grid absolute inset-0 opacity-10" /><div className="program-ring absolute -right-48 top-10 hidden size-[520px] rounded-full opacity-70 blur-2xl md:block" /><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_0.82fr] lg:items-center"><MotionReveal><p className="section-kicker-dark">{c.heroKicker}</p><h1 className="section-heading mt-4 max-w-4xl text-white">{c.heroTitle}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/72 sm:text-lg sm:leading-8">{c.heroBody}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={localePath(locale, "/contact")} className="button-primary">{c.heroPrimary} <CalendarCheck size={18} aria-hidden /></Link><a href="#student-stories" className="button-secondary">{c.heroSecondary} <ArrowRight size={18} aria-hidden /></a></div></MotionReveal><MotionImagePanel delay={0.12} className="relative"><div className="image-sheen relative aspect-[4/3] overflow-hidden rounded-xl border border-white/14 bg-brand-blue p-2 shadow-2xl shadow-brand-navy/24 sm:p-3"><div className="relative h-full overflow-hidden rounded-lg"><Image src="/images/testimonial-graduates-alt.webp" alt={c.heroAlt} fill priority quality={82} sizes="(min-width: 1180px) 500px, (min-width: 1024px) 42vw, 100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-brand-navy/10" /></div></div></MotionImagePanel></div></section>;
}

function StatsBand({ c }: { c: Copy }) {
  return <section className="relative z-10 bg-[linear-gradient(to_bottom,var(--brand-navy)_0%,var(--brand-navy)_50%,var(--surface-cream)_50%,var(--surface-cream)_100%)] px-4 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl grid-cols-2 overflow-hidden rounded-xl border border-white/10 bg-brand-blue shadow-2xl shadow-brand-navy/12 lg:grid-cols-4">{c.stats.map((item, index) => <div key={item.label} className={`min-h-[7.5rem] border-r border-white/10 p-5 even:border-r-0 sm:min-h-[8.25rem] sm:p-6 lg:min-h-[9.25rem] lg:border-r lg:p-8 lg:last:border-r-0 ${index < 2 ? "border-b lg:border-b-0" : ""}`}><CountUpStat value={item.value} className="block font-heading text-[2rem] font-normal leading-none text-brand-teal-light sm:text-[2.2rem] lg:text-[2.35rem]" /><p className="mt-3 text-[0.68rem] font-extrabold uppercase leading-tight tracking-[0.08em] text-white/62 sm:text-xs">{item.label}</p></div>)}</div></section>;
}

function FeaturedStory({ c }: { c: Copy }) {
  const story = c.stories[0];
  return <section className="section-pad bg-surface-cream"><div className="section-container"><MotionReveal className="grid gap-6 lg:grid-cols-[0.78fr_1.22fr] lg:items-end"><div><p className="section-kicker">{c.featuredKicker}</p><h2 className="section-heading mt-3">{c.featuredTitle}</h2></div><p className="body-copy-lg max-w-2xl lg:justify-self-end">{c.featuredBody}</p></MotionReveal><MotionArticle className="mt-10 overflow-hidden rounded-xl bg-brand-navy text-white shadow-2xl shadow-brand-navy/14"><div className="grid lg:grid-cols-[0.95fr_1.05fr]"><div className="relative min-h-[18rem] bg-brand-blue sm:min-h-[22rem]"><Image src="/images/career-english-course.webp" alt={c.featuredImageAlt} fill quality={82} sizes="(min-width: 1180px) 540px, (min-width: 1024px) 46vw, 100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-brand-navy/16" /></div><div className="flex min-w-0 flex-col justify-between gap-7 p-6 sm:gap-9 sm:p-8 lg:p-10"><div><div className="flex gap-1 text-brand-teal-light" aria-label={c.stars}>{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={20} fill="currentColor" strokeWidth={1.8} aria-hidden />)}</div><Quote className="mt-6 text-brand-teal-light sm:mt-8" size={30} aria-hidden /><p className="mt-5 max-w-2xl font-heading text-[1.42rem] font-normal leading-[1.16] sm:text-[2rem]">&ldquo;{story.quote}&rdquo;</p></div><div className="border-t border-white/14 pt-5"><p className="font-heading text-2xl font-normal">{story.name}</p><p className="mt-1 text-sm font-semibold text-white/58">{story.role}</p><p className="mt-4 inline-flex items-center gap-2 rounded-md bg-brand-red px-3 py-2 text-sm font-extrabold text-white"><Sparkles size={15} aria-hidden />{story.result}</p></div></div></div></MotionArticle></div></section>;
}

function StoryGrid({ c }: { c: Copy }) {
  return <section id="student-stories" className="bg-surface-cream px-4 pb-16 sm:px-6 lg:px-8 lg:pb-24"><div className="mx-auto max-w-6xl"><MotionReveal className="mx-auto max-w-3xl text-center"><p className="section-kicker">{c.gridKicker}</p><h2 className="section-heading mt-3">{c.gridTitle}</h2></MotionReveal><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{c.stories.slice(1).map((story, index) => { const initials = story.name.replaceAll(".", "").split(" ").map((part) => part[0]).join(""); return <MotionArticle key={story.name} delay={index * 0.06} className="testimonial-editorial-card relative isolate flex min-h-full flex-col overflow-hidden rounded-xl border border-brand-teal/30 bg-brand-navy p-5 text-white shadow-xl shadow-brand-navy/10 sm:p-7"><div className="pointer-events-none absolute -right-16 -top-20 size-52 rounded-full border border-brand-teal/14" aria-hidden /><span className="pointer-events-none absolute right-7 top-7 font-heading text-3xl font-normal text-brand-teal-light/24" aria-hidden>{String(index + 1).padStart(2, "0")}</span><span className="pointer-events-none absolute right-9 top-[5.4rem] size-2 rotate-45 border border-brand-red/70" aria-hidden /><p className="relative z-10 max-w-[72%] text-xs font-extrabold uppercase tracking-[0.14em] text-brand-teal-light">{story.track}</p><div className="relative z-10 mt-10 grid size-12 place-items-center rounded-md border border-brand-teal/28 bg-white/[0.04] text-brand-teal-light sm:mt-12"><Quote size={23} strokeWidth={1.7} aria-hidden /></div><blockquote className="relative z-10 mt-7 flex-1"><p className="font-heading text-[1.42rem] font-normal leading-[1.42] text-white sm:text-[1.55rem]">&ldquo;{story.quote}&rdquo;</p></blockquote><div className="relative z-10 mt-8 border-t border-brand-teal/20 pt-5"><div className="flex flex-col gap-4 min-[420px]:flex-row min-[420px]:items-center min-[420px]:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-md border border-brand-teal/28 bg-white/[0.04] font-heading text-sm text-brand-teal-light">{initials}</span><div className="min-w-0"><p className="font-heading text-xl font-normal">{story.name}</p><p className="mt-1 text-[0.68rem] font-bold uppercase tracking-[0.1em] text-white/48">{story.role}</p></div></div><div className="flex shrink-0 gap-1 text-brand-teal-light" aria-label={c.stars}>{Array.from({ length: 5 }).map((_, starIndex) => <Star key={starIndex} size={14} fill="currentColor" strokeWidth={1.5} aria-hidden />)}</div></div><p className="mt-5 flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.08em] text-white/68"><Sparkles size={14} className="shrink-0 text-brand-red" aria-hidden />{story.result}</p></div></MotionArticle>; })}</div></div></section>;
}

function OutcomeSection({ c }: { c: Copy }) {
  return <section className="bg-brand-navy px-4 py-16 text-white sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><MotionReveal><p className="section-kicker-dark">{c.outcomeKicker}</p><h2 className="section-heading mt-3 text-white">{c.outcomeTitle}</h2><p className="mt-5 max-w-xl leading-7 text-white/68">{c.outcomeBody}</p></MotionReveal><div className="grid gap-4 sm:grid-cols-2">{c.outcomes.map((outcome, index) => <MotionArticle key={outcome} delay={index * 0.08} className="rounded-xl border border-white/12 bg-white/[0.06] p-5"><CheckCircle2 className="text-brand-teal-light" size={24} aria-hidden /><p className="mt-4 font-heading text-xl font-normal leading-tight">{outcome}</p></MotionArticle>)}</div></div></section>;
}

function FinalCTA({ locale, c }: { locale: Locale; c: Copy }) {
  const icons = [CheckCircle2, ShieldCheck, Sparkles];
  return <section className="bg-surface-cream px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><MotionReveal className="mx-auto max-w-6xl overflow-hidden rounded-xl bg-brand-navy text-white shadow-2xl shadow-brand-navy/16"><div className="relative isolate grid gap-0 lg:grid-cols-[1.08fr_0.92fr]"><div className="p-6 sm:p-8 lg:p-10"><p className="section-kicker-dark">{c.finalKicker}</p><h2 className="mt-3 font-heading text-3xl font-normal leading-tight sm:text-4xl">{c.finalTitle}</h2><p className="mt-5 max-w-2xl leading-7 text-white/68">{c.finalBody}</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{c.finalItems.map((label, index) => { const Icon = icons[index]; return <span key={label} className="inline-flex items-center gap-2 rounded-md border border-white/12 bg-white/[0.07] px-3 py-2 text-sm font-bold text-white/78"><Icon size={16} className="text-brand-teal-light" aria-hidden />{label}</span>; })}</div></div><div className="flex flex-col justify-end gap-4 border-t border-white/10 bg-white/[0.05] p-6 sm:p-8 lg:border-l lg:border-t-0 lg:p-10"><div className="grid size-12 place-items-center rounded-lg bg-brand-teal text-white"><HeartHandshake size={24} aria-hidden /></div><p className="max-w-sm text-sm leading-6 text-white/62">{c.finalNote}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><Link href={localePath(locale, "/contact")} className="button-primary">{c.finalPrimary} <CalendarCheck size={18} aria-hidden /></Link><Link href={localePath(locale, "/programs#programs-hero")} className="button-secondary">{c.finalSecondary} <ArrowRight size={18} aria-hidden /></Link></div></div></div></MotionReveal></section>;
}
