import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarCheck, CheckCircle2, HeartHandshake, Quote, ShieldCheck, Sparkles, Star } from "lucide-react";
import { CountUpStat } from "@/components/count-up-stat";
import { MotionArticle, MotionImagePanel, MotionReveal } from "@/components/motion-reveal";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { localePath, type Locale } from "@/lib/i18n";
import { getRequestLocale } from "@/lib/i18n-server";
import { createLocalizedMetadata } from "@/lib/metadata";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getRequestLocale();
  return createLocalizedMetadata({
    locale,
    path: "/testimonials",
    ...(locale === "en"
      ? { title: "Student Results | Alberto Academy", description: "See how Alberto's students build confidence, clearer communication, and practical language skills, then explore Spanish lessons designed for real life." }
      : { title: "Testimonials | Alberto Academy", description: "Read student success stories from Alberto Academy, including confidence gains, academic progress, and career-ready English outcomes." }),
  });
}

const pageCopy = {
  es: {
    stats: [{ value: "200+", label: "Students taught" }, { value: "4+", label: "Years teaching" }, { value: "4", label: "Course levels" }, { value: "3", label: "Focused tracks" }],
    stories: [
      { name: "Camila M.", role: "Operations coordinator", quote: "The lessons helped me stop guessing. I finally understand how to organize my ideas before I speak.", result: "More confident meetings", track: "Career English" },
      { name: "Luis A.", role: "University student", quote: "Alberto corrected me without making me feel nervous. That changed how I participate in class.", result: "Stronger class participation", track: "Live Speaking" },
      { name: "Paola R.", role: "Customer success specialist", quote: "The materials felt personal. I practiced exactly the English I needed for interviews and work calls.", result: "Interview readiness", track: "Professional Fluency" },
      { name: "Daniel P.", role: "University applicant", quote: "The lessons were practical and focused. My writing improved, but my speaking improved even faster.", result: "IELTS speaking band +1.5", track: "Academic English" },
      { name: "Mariana R.", role: "Marketing professional", quote: "I stopped translating in my head during meetings. Alberto helped me speak with structure and confidence.", result: "Promotion interview passed", track: "Career English" },
      { name: "Sofia L.", role: "High school student", quote: "I used to avoid speaking English. Now I participate more, ask questions, and enjoy class.", result: "Top grade in English", track: "Academic English" },
    ],
    outcomes: ["Clearer pronunciation and sentence structure", "More confidence in meetings and interviews", "Better writing for school, work, and exams", "Personalized practice between live lessons"],
    heroKicker: "Student Results", heroTitle: "Real progress from students who needed English to feel practical.", heroBody: "These stories highlight the kind of progress Alberto Academy is built for: clearer speaking, stronger writing, better opportunities, and more confidence when English matters.", heroPrimary: "Book a Free Lesson", heroSecondary: "Read Stories", heroAlt: "Three happy adult English students in graduation clothes",
    featuredKicker: "Featured Story", featuredTitle: "Confidence students can feel outside class.", featuredBody: "The strongest results are not only grades or certificates. They show up when a student speaks with less hesitation, writes with more control, and finally uses English in real situations.", featuredImageAlt: "Professional student after improving English fluency", stars: "Five star testimonial",
    gridKicker: "More Student Stories", gridTitle: "Different goals, same focused method.", outcomeKicker: "What improves", outcomeTitle: "Progress that feels visible week by week.", outcomeBody: "Alberto Academy connects every lesson to a practical result, so students know what they are improving and how to keep practicing.",
    finalKicker: "Your turn", finalTitle: "Start with a trial lesson and leave with a clear path forward.", finalBody: "Alberto will review your level, goals, and schedule, then recommend the best English track for your next step.", finalItems: ["Level check", "Personal roadmap", "Focused feedback"], finalNote: "The first lesson helps identify what is working, what is missing, and what English path fits your goals.", finalPrimary: "Book a Free Lesson", finalSecondary: "Explore Programs",
  },
  en: {
    stats: [{ value: "400+", label: "Students taught" }, { value: "4+", label: "Years teaching" }, { value: "4", label: "Learning levels" }, { value: "3", label: "Flexible formats" }],
    stories: [
      { name: "Camila M.", role: "Operations coordinator", quote: "The lessons helped me stop guessing. I finally understand how to organize my ideas before I speak.", result: "More confident meetings", track: "Career English" },
      { name: "Luis A.", role: "University student", quote: "Alberto corrected me without making me feel nervous. That changed how I participate in class.", result: "Stronger class participation", track: "Live Speaking" },
      { name: "Paola R.", role: "Customer success specialist", quote: "The materials felt personal. I practiced exactly the English I needed for interviews and work calls.", result: "Interview readiness", track: "Professional Fluency" },
      { name: "Daniel P.", role: "University applicant", quote: "The lessons were practical and focused. My writing improved, but my speaking improved even faster.", result: "IELTS speaking band +1.5", track: "Academic English" },
      { name: "Mariana R.", role: "Marketing professional", quote: "I stopped translating in my head during meetings. Alberto helped me speak with structure and confidence.", result: "Promotion interview passed", track: "Career English" },
      { name: "Sofia L.", role: "High school student", quote: "I used to avoid speaking English. Now I participate more, ask questions, and enjoy class.", result: "Top grade in English", track: "Academic English" },
    ],
    outcomes: ["Clearer pronunciation and sentence structure", "More confidence in meetings and interviews", "Better writing for school, work, and exams", "Personalized practice between live lessons"],
    heroKicker: "Student results", heroTitle: "A teaching method students can feel beyond class.", heroBody: "These real student stories show Alberto's communication-first approach in practice. The same structured, supportive method guides every Spanish lesson.", heroPrimary: "Book a Free Consultation", heroSecondary: "Read Stories", heroAlt: "Three happy adult language students celebrating their progress",
    featuredKicker: "Featured story", featuredTitle: "Confidence that follows you beyond the lesson.", featuredBody: "The strongest results appear when a student speaks with less hesitation, writes with more control, and uses the language in real situations.", featuredImageAlt: "Professional language student after building greater confidence", stars: "Five-star testimonial",
    gridKicker: "More student stories", gridTitle: "Different goals. One practical method.", outcomeKicker: "What improves", outcomeTitle: "Progress you can notice from week to week.", outcomeBody: "Every lesson connects to a practical result, so students know what is improving and what to practice next.",
    finalKicker: "Your turn", finalTitle: "Start with a free consultation and leave with a clear Spanish path.", finalBody: "Alberto will review your level, goals, and schedule, then recommend the learning format that fits your next step.", finalItems: ["Level guidance", "Personal roadmap", "Focused feedback"], finalNote: "The consultation identifies what you already know, what you need most, and which Spanish program fits your goals.", finalPrimary: "Book a Free Consultation", finalSecondary: "Explore Programs",
  },
};

export default async function TestimonialsPage() {
  const locale = await getRequestLocale();
  const c = pageCopy[locale];
  return <main className="min-h-screen bg-surface-cream text-brand-navy"><SiteHeader locale={locale} /><Hero locale={locale} c={c} /><StatsBand c={c} /><FeaturedStory c={c} /><StoryGrid c={c} /><OutcomeSection c={c} /><FinalCTA locale={locale} c={c} /><SiteFooter locale={locale} /></main>;
}

type Copy = (typeof pageCopy)[Locale];

function Hero({ locale, c }: { locale: Locale; c: Copy }) {
  return <section id="testimonials-hero" className="relative isolate overflow-hidden bg-brand-navy px-4 pb-20 pt-14 text-white sm:px-6 sm:pb-24 sm:pt-16 lg:px-8 lg:pb-32 lg:pt-20"><div className="orbital-grid absolute inset-0 opacity-10" /><div className="program-ring absolute -right-48 top-10 hidden size-[520px] rounded-full opacity-70 blur-2xl md:block" /><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_0.82fr] lg:items-center"><MotionReveal><p className="section-kicker-dark">{c.heroKicker}</p><h1 className="section-heading mt-4 max-w-4xl text-white">{c.heroTitle}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/72 sm:text-lg sm:leading-8">{c.heroBody}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={localePath(locale, "/contact")} className="button-primary">{c.heroPrimary} <CalendarCheck size={18} aria-hidden /></Link><a href="#student-stories" className="button-secondary">{c.heroSecondary} <ArrowRight size={18} aria-hidden /></a></div></MotionReveal><MotionImagePanel delay={0.12} className="relative"><div className="image-sheen relative aspect-[4/3] overflow-hidden rounded-xl border border-white/14 bg-brand-blue p-2 shadow-2xl shadow-brand-navy/24 sm:p-3"><div className="relative h-full overflow-hidden rounded-lg"><Image src="/images/testimonial-graduates-alt.webp" alt={c.heroAlt} fill priority quality={82} sizes="(min-width: 1180px) 500px, (min-width: 1024px) 42vw, 100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-brand-navy/10" /></div></div></MotionImagePanel></div></section>;
}

function StatsBand({ c }: { c: Copy }) {
  return <section className="relative z-10 bg-[linear-gradient(to_bottom,var(--brand-navy)_0%,var(--brand-navy)_50%,var(--surface-cream)_50%,var(--surface-cream)_100%)] px-4 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl grid-cols-2 overflow-hidden rounded-xl border border-white/10 bg-brand-blue shadow-2xl shadow-brand-navy/12 lg:grid-cols-4">{c.stats.map((item, index) => <div key={item.label} className={`min-h-[7.5rem] border-r border-white/10 p-5 even:border-r-0 sm:min-h-[8.25rem] sm:p-6 lg:min-h-[9.25rem] lg:border-r lg:p-8 lg:last:border-r-0 ${index < 2 ? "border-b lg:border-b-0" : ""}`}><CountUpStat value={item.value} className="block font-heading text-[2rem] font-normal leading-none text-brand-teal-light sm:text-[2.2rem] lg:text-[2.35rem]" /><p className="mt-3 text-[0.68rem] font-extrabold uppercase leading-tight tracking-[0.08em] text-white/62 sm:text-xs">{item.label}</p></div>)}</div></section>;
}

function FeaturedStory({ c }: { c: Copy }) {
  const story = c.stories[4];
  return <section className="section-pad bg-surface-cream"><div className="section-container"><MotionReveal className="grid gap-6 lg:grid-cols-[0.78fr_1.22fr] lg:items-end"><div><p className="section-kicker">{c.featuredKicker}</p><h2 className="section-heading mt-3">{c.featuredTitle}</h2></div><p className="body-copy-lg max-w-2xl lg:justify-self-end">{c.featuredBody}</p></MotionReveal><MotionArticle className="mt-10 overflow-hidden rounded-xl bg-brand-navy text-white shadow-2xl shadow-brand-navy/14"><div className="grid lg:grid-cols-[0.95fr_1.05fr]"><div className="relative min-h-[18rem] bg-brand-blue sm:min-h-[22rem]"><Image src="/images/career-english-course.webp" alt={c.featuredImageAlt} fill quality={82} sizes="(min-width: 1180px) 540px, (min-width: 1024px) 46vw, 100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-brand-navy/16" /></div><div className="flex min-w-0 flex-col justify-between gap-7 p-6 sm:gap-9 sm:p-8 lg:p-10"><div><div className="flex gap-1 text-brand-teal-light" aria-label={c.stars}>{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={20} fill="currentColor" strokeWidth={1.8} aria-hidden />)}</div><Quote className="mt-6 text-brand-teal-light sm:mt-8" size={30} aria-hidden /><p className="mt-5 max-w-2xl font-heading text-[1.42rem] font-normal leading-[1.16] sm:text-[2rem]">&ldquo;{story.quote}&rdquo;</p></div><div className="border-t border-white/14 pt-5"><p className="font-heading text-2xl font-normal">{story.name}</p><p className="mt-1 text-sm font-semibold text-white/58">{story.role}</p><p className="mt-4 inline-flex items-center gap-2 rounded-md bg-brand-red px-3 py-2 text-sm font-extrabold text-white"><Sparkles size={15} aria-hidden />{story.result}</p></div></div></div></MotionArticle></div></section>;
}

function StoryGrid({ c }: { c: Copy }) {
  return <section id="student-stories" className="bg-surface-cream px-4 pb-16 sm:px-6 lg:px-8 lg:pb-24"><div className="mx-auto max-w-6xl"><MotionReveal className="mx-auto max-w-3xl text-center"><p className="section-kicker">{c.gridKicker}</p><h2 className="section-heading mt-3">{c.gridTitle}</h2></MotionReveal><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{c.stories.map((story, index) => { const initials = story.name.replaceAll(".", "").split(" ").map((part) => part[0]).join(""); return <MotionArticle key={story.name} delay={index * 0.06} className="testimonial-editorial-card relative isolate flex min-h-full flex-col overflow-hidden rounded-xl border border-brand-teal/30 bg-brand-navy p-5 text-white shadow-xl shadow-brand-navy/10 sm:p-7"><div className="pointer-events-none absolute -right-16 -top-20 size-52 rounded-full border border-brand-teal/14" aria-hidden /><span className="pointer-events-none absolute right-7 top-7 font-heading text-3xl font-normal text-brand-teal-light/24" aria-hidden>{String(index + 1).padStart(2, "0")}</span><span className="pointer-events-none absolute right-9 top-[5.4rem] size-2 rotate-45 border border-brand-red/70" aria-hidden /><p className="relative z-10 max-w-[72%] text-xs font-extrabold uppercase tracking-[0.14em] text-brand-teal-light">{story.track}</p><div className="relative z-10 mt-10 grid size-12 place-items-center rounded-md border border-brand-teal/28 bg-white/[0.04] text-brand-teal-light sm:mt-12"><Quote size={23} strokeWidth={1.7} aria-hidden /></div><blockquote className="relative z-10 mt-7 flex-1"><p className="font-heading text-[1.42rem] font-normal leading-[1.42] text-white sm:text-[1.55rem]">&ldquo;{story.quote}&rdquo;</p></blockquote><div className="relative z-10 mt-8 border-t border-brand-teal/20 pt-5"><div className="flex flex-col gap-4 min-[420px]:flex-row min-[420px]:items-center min-[420px]:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-md border border-brand-teal/28 bg-white/[0.04] font-heading text-sm text-brand-teal-light">{initials}</span><div className="min-w-0"><p className="font-heading text-xl font-normal">{story.name}</p><p className="mt-1 text-[0.68rem] font-bold uppercase tracking-[0.1em] text-white/48">{story.role}</p></div></div><div className="flex shrink-0 gap-1 text-brand-teal-light" aria-label={c.stars}>{Array.from({ length: 5 }).map((_, starIndex) => <Star key={starIndex} size={14} fill="currentColor" strokeWidth={1.5} aria-hidden />)}</div></div><p className="mt-5 flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.08em] text-white/68"><Sparkles size={14} className="shrink-0 text-brand-red" aria-hidden />{story.result}</p></div></MotionArticle>; })}</div></div></section>;
}

function OutcomeSection({ c }: { c: Copy }) {
  return <section className="bg-brand-navy px-4 py-16 text-white sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><MotionReveal><p className="section-kicker-dark">{c.outcomeKicker}</p><h2 className="section-heading mt-3 text-white">{c.outcomeTitle}</h2><p className="mt-5 max-w-xl leading-7 text-white/68">{c.outcomeBody}</p></MotionReveal><div className="grid gap-4 sm:grid-cols-2">{c.outcomes.map((outcome, index) => <MotionArticle key={outcome} delay={index * 0.08} className="rounded-xl border border-white/12 bg-white/[0.06] p-5"><CheckCircle2 className="text-brand-teal-light" size={24} aria-hidden /><p className="mt-4 font-heading text-xl font-normal leading-tight">{outcome}</p></MotionArticle>)}</div></div></section>;
}

function FinalCTA({ locale, c }: { locale: Locale; c: Copy }) {
  const icons = [CheckCircle2, ShieldCheck, Sparkles];
  return <section className="bg-surface-cream px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><MotionReveal className="mx-auto max-w-6xl overflow-hidden rounded-xl bg-brand-navy text-white shadow-2xl shadow-brand-navy/16"><div className="relative isolate grid gap-0 lg:grid-cols-[1.08fr_0.92fr]"><div className="p-6 sm:p-8 lg:p-10"><p className="section-kicker-dark">{c.finalKicker}</p><h2 className="mt-3 font-heading text-3xl font-normal leading-tight sm:text-4xl">{c.finalTitle}</h2><p className="mt-5 max-w-2xl leading-7 text-white/68">{c.finalBody}</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{c.finalItems.map((label, index) => { const Icon = icons[index]; return <span key={label} className="inline-flex items-center gap-2 rounded-md border border-white/12 bg-white/[0.07] px-3 py-2 text-sm font-bold text-white/78"><Icon size={16} className="text-brand-teal-light" aria-hidden />{label}</span>; })}</div></div><div className="flex flex-col justify-end gap-4 border-t border-white/10 bg-white/[0.05] p-6 sm:p-8 lg:border-l lg:border-t-0 lg:p-10"><div className="grid size-12 place-items-center rounded-lg bg-brand-teal text-white"><HeartHandshake size={24} aria-hidden /></div><p className="max-w-sm text-sm leading-6 text-white/62">{c.finalNote}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><Link href={localePath(locale, "/contact")} className="button-primary">{c.finalPrimary} <CalendarCheck size={18} aria-hidden /></Link><Link href={localePath(locale, "/programs#programs-hero")} className="button-secondary">{c.finalSecondary} <ArrowRight size={18} aria-hidden /></Link></div></div></div></MotionReveal></section>;
}
